

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "53:53/udp"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LS_AUTH_TOKEN}
      - DEBUG=${DEBUG}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - public_net
      - private_net

  mongodb:
    image: mongo:latest
    container_name: private_data_tier
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    networks:
      - private_net
    # No ports exposed = Private Data Subnet

networks:
  public_net:
  private_net: