#!/bin/bash
set -e
echo "🧹 Cleaning up existing environment..."

# 1. Kill lingering Terraform processes
killall terraform 2>/dev/null || true
sleep 1

# 2. Destroy existing cloud resources
if [ -f terraform.tfstate ]; then
    echo "🗑️  Tearing down existing cloud resources..."
    terraform destroy -auto-approve -lock=false || true
fi

# 3. Wipe Terraform state and temp files
rm -f .terraform.tfstate.lock.info
rm -rf .terraform/
rm -f terraform.tfstate*
rm -f lambda_auth.zip lambda_accounts.zip lambda_transactions.zip lambda_notifications.zip lambda_kyc.zip lambda_dlq.zip lambda.zip

# 4. Reset containers
docker-compose down -v
docker-compose up -d

echo "⏳ Waiting for LocalStack Pro (S3, Cognito, RDS, …)..."
MAX_RETRIES=40
COUNT=0
while ! curl -s http://localhost:4566/_localstack/health | grep -q '"s3": "available"'; do
    if [ $COUNT -ge $MAX_RETRIES ]; then
        echo "❌ LocalStack failed to start in time."
        exit 1
    fi
    echo -n "."
    sleep 3
    COUNT=$((COUNT+1))
done
echo -e "\n✅ LocalStack Pro is READY."

# ──────────────────────────────────────────────────────────────────────────────
# 5. Package Lambda functions
# ──────────────────────────────────────────────────────────────────────────────

package_lambda() {
    local name=$1
    local needs_pymongo=$2
    local needs_xray=$3
    echo "📦 Packaging lambda_${name}..."
    rm -rf "_pkg_${name}"
    mkdir "_pkg_${name}"
    if [ "$needs_pymongo" = "true" ]; then
        pip3 install --target "./_pkg_${name}" pymongo > /dev/null
    fi
    if [ "$needs_xray" = "true" ]; then
        pip install --target "./_pkg_${name}" aws-xray-sdk > /dev/null
    fi
    cp "lambdas/${name}.py" "./_pkg_${name}/${name}.py"
    (cd "_pkg_${name}" && zip -r "../lambda_${name}.zip" . > /dev/null)
    rm -rf "_pkg_${name}"
    echo "   ✅ lambda_${name}.zip"
}

package_lambda "auth"          "false" "true"
package_lambda "accounts"      "false" "true"
package_lambda "transactions"  "true"  "true"
package_lambda "notifications" "false" "true"
package_lambda "kyc"           "false" "true"
package_lambda "dlq"           "false" "true"

# ──────────────────────────────────────────────────────────────────────────────
# 6. Deploy infrastructure
# ──────────────────────────────────────────────────────────────────────────────
echo "🏗️  Deploying infrastructure..."
terraform init -upgrade
terraform apply -auto-approve -lock=false

# ──────────────────────────────────────────────────────────────────────────────
# 7. Auto-inject API URL into config.js (loaded by index.html)
# ──────────────────────────────────────────────────────────────────────────────
API_URL=$(terraform output -raw api_base_url)
ALB_URL=$(terraform output -raw alb_base_url)

cat > config.js <<EOF
// Auto-generated by reset.sh — do not edit manually
window.BANK_CONFIG = {
  apiBase:         "${API_URL}",
  albBase:         "${ALB_URL}",
  cognitoPoolId:   "$(terraform output -raw cognito_user_pool_id)",
  cognitoClientId: "$(terraform output -raw cognito_client_id)",
  rdsEndpoint:     "$(terraform output -raw rds_endpoint)",
  redisEndpoint:   "$(terraform output -raw redis_endpoint)"
};
EOF

echo ""
echo "════════════════════════════════════════════════════════"
echo "✅  Deployment complete!"
echo "════════════════════════════════════════════════════════"
echo ""
echo "📋  API Gateway Endpoints:"
terraform output api_base_url
terraform output api_auth_url
terraform output api_accounts_url
terraform output api_transactions_url
terraform output api_notifications_url
terraform output api_kyc_url
echo ""
echo "⚖️   Load Balancer Endpoints:"
terraform output alb_base_url
terraform output alb_auth_url
terraform output alb_accounts_url
terraform output alb_transactions_url
terraform output alb_notifications_url
terraform output alb_kyc_url
echo ""
echo "🔑  Cognito:"
terraform output cognito_user_pool_id
terraform output cognito_client_id
echo ""
echo "✅  config.js written — open index.html directly in your browser."
echo "════════════════════════════════════════════════════════"
