@echo off
setlocal enabledelayedexpansion

echo Cleaning up existing environment...

REM 1. Kill lingering Terraform processes
taskkill /F /IM terraform.exe /T >nul 2>&1
timeout /t 1 /nobreak >nul

REM 2. Destroy existing cloud resources
IF EXIST "terraform.tfstate" (
    echo Tearing down existing cloud resources...
    terraform destroy -auto-approve -lock=false
)

REM 3. Wipe state and temp files
if exist ".terraform.tfstate.lock.info" del /f /q ".terraform.tfstate.lock.info"
if exist ".terraform\"                  rd  /s /q ".terraform"
if exist "terraform.tfstate"            del /f /q "terraform.tfstate"
if exist "terraform.tfstate.backup"     del /f /q "terraform.tfstate.backup"
if exist "lambda_auth.zip"              del /f /q "lambda_auth.zip"
if exist "lambda_accounts.zip"          del /f /q "lambda_accounts.zip"
if exist "lambda_transactions.zip"      del /f /q "lambda_transactions.zip"
if exist "lambda_notifications.zip"     del /f /q "lambda_notifications.zip"
if exist "lambda_kyc.zip"               del /f /q "lambda_kyc.zip"
if exist "lambda_dlq.zip"               del /f /q "lambda_dlq.zip"
if exist "lambda.zip"                   del /f /q "lambda.zip"

REM 4. Reset containers
docker-compose down -v
docker-compose up -d

echo Waiting for LocalStack Pro...
set MAX_RETRIES=40
set COUNT=0

:healthcheck
curl -s http://localhost:4566/_localstack/health | findstr /C:"\"s3\": \"available\"" >nul
if %ERRORLEVEL% EQU 0 goto :ready

set /a COUNT+=1
if %COUNT% GEQ %MAX_RETRIES% (
    echo LocalStack failed to start in time.
    exit /b 1
)
<nul set /p=.
timeout /t 3 /nobreak >nul
goto :healthcheck

:ready
echo.
echo LocalStack Pro is READY.

REM ─────────────────────────────────────────────────────────────────────────────
REM 5. Package Lambda functions
REM ─────────────────────────────────────────────────────────────────────────────

CALL :package_lambda auth         false
CALL :package_lambda accounts     false
CALL :package_lambda transactions true
CALL :package_lambda notifications false
CALL :package_lambda kyc          false
CALL :package_lambda dlq          false

REM ─────────────────────────────────────────────────────────────────────────────
REM 6. Deploy infrastructure
REM ─────────────────────────────────────────────────────────────────────────────
echo Deploying infrastructure...
terraform init -upgrade
terraform apply -auto-approve -lock=false

REM ─────────────────────────────────────────────────────────────────────────────
REM 7. Write config.js so index.html picks up the API URL automatically
REM ─────────────────────────────────────────────────────────────────────────────
for /f "delims=" %%i in ('terraform output -raw api_base_url')         do set API_URL=%%i
for /f "delims=" %%i in ('terraform output -raw cognito_user_pool_id') do set POOL_ID=%%i
for /f "delims=" %%i in ('terraform output -raw cognito_client_id')    do set CLIENT_ID=%%i
for /f "delims=" %%i in ('terraform output -raw rds_endpoint')         do set RDS_EP=%%i
for /f "delims=" %%i in ('terraform output -raw redis_endpoint')       do set REDIS_EP=%%i

(
    echo // Auto-generated by reset.bat -- do not edit manually
    echo window.BANK_CONFIG = {
    echo   apiBase:         "%API_URL%",
    echo   cognitoPoolId:   "%POOL_ID%",
    echo   cognitoClientId: "%CLIENT_ID%",
    echo   rdsEndpoint:     "%RDS_EP%",
    echo   redisEndpoint:   "%REDIS_EP%"
    echo };
) > config.js

echo.
echo ================================================
echo  Deployment complete!
echo ================================================
echo.
echo API Endpoints:
terraform output api_base_url
terraform output api_auth_url
terraform output api_accounts_url
terraform output api_transactions_url
terraform output api_notifications_url
terraform output api_kyc_url
echo.
echo Cognito:
terraform output cognito_user_pool_id
terraform output cognito_client_id
echo.
echo config.js written. Open index.html in your browser.
echo ================================================

goto :EOF

REM ─────────────────────────────────────────────────────────────────────────────
REM Subroutine: package_lambda <name> <needs_pymongo>
REM ─────────────────────────────────────────────────────────────────────────────
:package_lambda
set _NAME=%~1
set _PYMONGO=%~2

echo Packaging lambda_%_NAME%...
if exist "_pkg_%_NAME%" rd /s /q "_pkg_%_NAME%"
mkdir "_pkg_%_NAME%"

if "%_PYMONGO%"=="true" (
    pip install --target "%CD%\_pkg_%_NAME%" pymongo >nul
)

copy "lambdas\%_NAME%.py" "_pkg_%_NAME%\%_NAME%.py" >nul
powershell -Command "Compress-Archive -Path '_pkg_%_NAME%\*' -DestinationPath 'lambda_%_NAME%.zip' -Force"
rd /s /q "_pkg_%_NAME%"
echo    OK lambda_%_NAME%.zip
GOTO :EOF
